s=set()
n=input("Enter a no:")
s.add(int(n))
n=input("Enter a no:")
s.add(int(n))
n=input("Enter a no:")
s.add(int(n))
n=input("Enter a no:")
s.add(int(n))
n=input("Enter a no:")
s.add(int(n))
print(s)